language: cpp
compiler:
  - gcc

os:
  - linux

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-sdk-team/ppa
  - sudo add-apt-repository -y ppa:george-edison55/gcc4.7-precise
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu trusty-backports main universe"
  - sudo apt-get update

install:
  - sudo apt-get install -y gcc-4.7 g++-4.7
  - sudo apt-get remove -y g++-4.6 gcc-4.6

script:
  - make
